# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a517f117714d8991343a438b1823e092280d5beb383eddeda6d8fffe8d107b1efbf63555dc3382dadfb6037434b0f98abdc1f7c7a7d14191842a43c3e8ba28fb

test:
  secret_key_base: 31862131097656d53b08b166bd49059834e04aba486789a485846d4dc53f4efeb43f16dcc04775fe551d4a691c8d28a0c78f9b8730bd2020b571d39971403bb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
